apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  managementState: Managed
  storage:
    pvc:
      claim: {{ .Values.pvc }}
  rolloutStrategy: Recreate
  replicas: 1