kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc }}
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nutanix-volume