# NOTE: This file will be edited by the pipeline processes as new versions are built through the pipelines
# prod_version and test_version keys with built values will be edited when the pipelines run
---
iot_consumer:
  tag: 0.3.2-8
  built_tags:
    - 0.3.2-7
    - 0.3.2-8
