# NOTE: This file will be edited by the pipeline processes as new versions are built through the pipelines
# prod_version and test_version keys with built values will be edited when the pipelines run
---
iot_anomaly_detection:
  tag: 0.3.2-33
  built_tags:
    - 0.3.2-32
    - 0.3.2-33
iot_consumer:
  tag: 0.3.2-50
  built_tags:
    - 0.3.2-50
iot_frontend:
  tag: 0.3.1-38
  built_tags:
    - 0.3.1-38
