clusterGroup:
  name: datacenter
  isHubCluster: true

  namespaces:
  - golang-external-secrets
  - external-secrets
  - open-cluster-management
  - manuela-ml-workspace
  - manuela-tst-all
  - manuela-ci
  - manuela-data-lake
  - staging
  - vault

  operatorgroupExcludes:
  - manuela-ml-workspace

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management

    amqbroker-prod:
      name: amq-broker-rhel8
      namespace: manuela-tst-all

    amqstreams-prod-dev:
      name: amq-streams
      namespaces: 
      - manuela-data-lake
      - manuela-tst-all

    camelk-prod-dev:
      name: red-hat-camel-k
      namespaces: 
      - manuela-data-lake
      - manuela-tst-all

    seldon-prod-dev:
      name: seldon-operator-certified
      namespaces: 
      - openshift-operators
      source: certified-operators

    pipelines:
      name: openshift-pipelines-operator-rh
      source: redhat-operators
      
    odh:
      name: opendatahub-operator
      source: community-operators

  projects:
  - datacenter
  - production-datalake
  - golang-external-secrets
  - vault

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: datacenter
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
        - /spec/loggingCA

    odh:
      name: odh
      namespace: manuela-ml-workspace
      project: datacenter
      path: charts/datacenter/opendatahub

    pipelines:
      name: pipelines
      namespace: manuela-ci
      project: datacenter
      path: charts/datacenter/pipelines

    production-data-lake:
      name: production-data-lake
      namespace: manuela-data-lake
      project: production-datalake
      path: charts/datacenter/manuela-data-lake
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      - group: route.openshift.io
        kind: Route
        jsonPointers:
        - /status
      - group: image.openshift.io
        kind: ImageStream
        jsonPointers:
        - /spec/tags
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
        - /spec/template/spec/containers/0/image

    test:
      name: manuela-test
      namespace: manuela-tst-all
      project: datacenter
      path: charts/datacenter/manuela-tst
      extraValueFiles:
        - /overrides/values-test-imagedata.yaml

    vault:
      name: vault
      namespace: vault
      project: datacenter
      path: common/hashicorp-vault

    secrets-operator:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: golang-external-secrets
      path: common/golang-external-secrets

    secrets:
      name: external-secrets
      namespace: external-secrets
      project: golang-external-secrets
      path: charts/datacenter/external-secrets

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main

  managedClusterGroups:
    factory:
      name: factory
      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
      # targetRevision: main
      helmOverrides:
      # Values must be strings!
      - name: clusterGroup.isHubCluster
        value: "false"
      clusterSelector:
        matchLabels:
          clusterGroup: factory
        matchExpressions:
        - key: vendor
          operator: In
          values:
            - OpenShift

