main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: wolfgangntnx
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: wolfganghuse
    #username: PLAINTEXT
    email: wolfgang.huse@nutanix.com
    dev_revision: main

  s3:
    bucket:
      name: industrial-edge-1
      region: us-east-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: true
          url: objects.blaze.dachlab.net
