{{- /*
The nutanixSecret variable is going to be parsed by ESO and not by Argo, hence the whole printf and escaping
So first Argo will render the template, then ESO will parse the functions inside the curly brackets
and resolve variables and functions.
*/}}
{{- $nutanixSecret := printf "{{ cat .pe_endpoint `:9440:` .pe_username `:` .pe_password }}" }}

apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ntnx-secret
  namespace: openshift-cluster-csi-drivers
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: ntnx-secret
    template:
      type: Opaque
      data:
        #key: "{{ $nutanixSecret }}"
        key: "{{"{{"}} .pe_endpoint {{"}}"}}:9440:{{"{{"}} .pe_username {{"}}"}}:{{"{{"}} .pe_password {{"}}"}}"
  dataFrom:
  - extract:
      key: {{ .Values.nutanixsecret.key }}
