apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ntnx-secret
  namespace: openshift-cluster-csi-drivers
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: ntnx-secret
    template:
      type: Opaque
      data:
        key: "{{"{{"}} .pe_endpoint {{"}}"}}:9440:{{"{{"}} .pe_username {{"}}"}}:{{"{{"}} .pe_password {{"}}"}}"
  dataFrom:
  - extract:
      key: {{ .Values.nutanixsecret.key }}
