apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-iot-frontend
spec:
  workspaces:
  - name: gitrepos
  - name: config
  - name: build-artifacts

  tasks:
  - name: git-clone-dev
    taskRef:
      name: git-clone-with-tags
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: GIT_DEV_REPO_URL
    - name: revision
      value: {{ .Values.global.git.dev_revision }}
    - name: subdirectory
      value: dev
    - name: deleteExisting
      value: "true"

  - name: git-clone-ops
    taskRef:
      name: git-clone-with-tags
    runAfter:
    - git-clone-dev
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: GIT_OPS_REPO_TEST_URL
    - name: revision
      value: {{ .Values.global.targetRevision }}
    - name: subdirectory
      value: ops
    - name: deleteExisting
      value: "true"

  - name: bump-build-version-iot-frontend
    taskRef:
      name: bumpversion
    runAfter:
    - git-clone-ops
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: component_name
      value: iot-frontend
    - name: version_file_path
      value: components/iot-frontend/VERSION

  - name: s2i-build-iot-frontend
    taskRef:
      name: s2i
    runAfter:
    - bump-build-version-iot-frontend
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: build-artifacts
      workspace: build-artifacts
    params:
    - name: TLSVERIFY
      value: "false"
    - name: PATH_CONTEXT
      value: components/iot-frontend
    - name: BUILDER_IMAGE
      value: nodeshift/ubi8-s2i-web-app
    - name: CHAINED_BUILD_DOCKERFILE
      value: "FROM quay.io/manuela/httpd-ionic\nCOPY --from=0 /opt/app-root/output /var/www/html/"
    - name: TAG
      value: $(tasks.bump-build-version-iot-frontend.results.image-tag)
    - name: OUTPUT_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/line-dashboard

  - name: copy-image-to-remote-registry-iot-frontend
    taskRef:
      name: skopeo-copy
    runAfter:
    - s2i-build-iot-frontend
    workspaces:
    - name: config
      workspace: config
    params:
    - name: TAG
      value: $(tasks.bump-build-version-iot-frontend.results.image-tag)
    - name: SOURCE_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/line-dashboard
    - name: TARGET_IMAGE_CONFIGMAPKEY
      value: IOT_FRONTEND_IMAGE

  - name: push-dev-tag
    taskRef:
      name: github-push
    runAfter:
    - copy-image-to-remote-registry-iot-frontend
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: PUSH_FLAGS
      value: --tags


  - name: modify-ops-test-iot-frontend
    taskRef:
      name: gitops-imagetag
    runAfter:
    - push-dev-tag
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: IOT_FRONTEND
    - name: ENVIRONMENT
      value: TEST
    - name: TAG
      value: $(tasks.bump-build-version-iot-frontend.results.image-tag)
    - name: subdirectory
      value: ops

  - name: commit-ops
    taskRef:
      name: git-commit
    runAfter:
    - modify-ops-test-iot-frontend
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: subdirectory
      value: ops

  - name: push-ops
    taskRef:
      name: github-push
    runAfter:
    - commit-ops
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: subdirectory
      value: ops
